[package]
name = "tmtc-c2a"
version.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
funty = "2"
anyhow = { version = "1", features = ["backtrace"] }
async-trait = "0.1"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4", features = ["derive", "env"] }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
http.workspace = true
tower.workspace = true
tower-http = { workspace = true, features = ["trace", "cors"] }
tokio = { version = "1", features = ["full"] }
prost.workspace = true
prost-types.workspace = true
tonic = { workspace = true, features = ["tls-native-roots", "tls-webpki-roots"] }
tonic-health.workspace = true
tonic-reflection.workspace = true
tonic-web.workspace = true
axum = { workspace = true, default-features = false, features = ["http1", "tokio"] }
mime_guess = "2.0.4"
sentry = { version = "0.34", default-features = false, features = ["backtrace", "contexts", "panic", "rustls", "reqwest"] }
sentry-tracing = "0.34"
tlmcmddb = "=2.5.1"
structpack.workspace = true
gaia-ccsds-c2a.workspace = true
gaia-tmtc.workspace = true
kble-socket = { version = "0.3.0", features = ["tungstenite"] }
tokio-tungstenite = "0.20.1"
itertools = "0.12.1"
uuid = { version = "1", features = ["v4"] }

[build-dependencies]
tonic-build.workspace = true
